from __future__ import annotations

import json
import threading
import time
import uuid
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from .config import ROOT


class TelemetryStore:
    """Local observability sink designed for Alloy/Loki and Prometheus textfile collection."""

    def __init__(self, runtime_root: Path | None = None) -> None:
        self.root = runtime_root or ROOT / "runtime"
        self.log_path = self.root / "logs" / "agent-events.jsonl"
        self.metrics_path = self.root / "metrics" / "granted_game.prom"
        self.trajectory_dir = self.root / "trajectories"
        self._lock = threading.Lock()
        self._counters: Counter[str] = Counter()
        self._last_latency_ms = 0.0
        self._last_server_ttfa_ms = 0.0
        self._last_client_ttfa_ms = 0.0
        self._last_monty_execution_ms = 0.0
        self._ttfa_slo_ms = 2000.0

    @staticmethod
    def now() -> str:
        return datetime.now(UTC).isoformat()

    def event(self, event: str, request_id: str, **fields: Any) -> None:
        record = {"timestamp": self.now(), "event": event, "request_id": request_id, **fields}
        with self._lock:
            self.log_path.parent.mkdir(parents=True, exist_ok=True)
            with self.log_path.open("a", encoding="utf-8") as handle:
                handle.write(json.dumps(record, ensure_ascii=False, separators=(",", ":")) + "\n")

    def count(self, metric: str, amount: int = 1, labels: dict[str, str] | None = None) -> None:
        label_text = ""
        if labels:
            values = ",".join(f'{key}="{value}"' for key, value in sorted(labels.items()))
            label_text = "{" + values + "}"
        with self._lock:
            self._counters[f"{metric}{label_text}"] += amount
            self._write_metrics()

    def latency(self, milliseconds: float) -> None:
        with self._lock:
            self._last_latency_ms = milliseconds
            self._write_metrics()

    def monty_execution(self, milliseconds: float, *, failed: bool = False) -> None:
        with self._lock:
            self._last_monty_execution_ms = milliseconds
            self._counters["granted_agent_monty_executions_total"] += 1
            if failed:
                self._counters["granted_agent_monty_execution_errors_total"] += 1
            self._write_metrics()

    def first_action(self, milliseconds: float, *, observed_by: str = "server") -> None:
        with self._lock:
            if observed_by == "client":
                self._last_client_ttfa_ms = milliseconds
                self._counters["granted_agent_client_ttfa_samples_total"] += 1
            else:
                self._last_server_ttfa_ms = milliseconds
                self._counters["granted_agent_server_ttfa_samples_total"] += 1
            if milliseconds > self._ttfa_slo_ms:
                self._counters[
                    f'granted_agent_ttfa_slo_violations_total{{observed_by="{observed_by}"}}'
                ] += 1
            self._write_metrics()

    def _write_metrics(self) -> None:
        self.metrics_path.parent.mkdir(parents=True, exist_ok=True)
        lines = ["# Generated by Granted Game; compatible with Prometheus textfile collectors."]
        lines.extend(f"{name} {value}" for name, value in sorted(self._counters.items()))
        lines.append(f"granted_agent_last_run_latency_milliseconds {self._last_latency_ms:.3f}")
        lines.append(
            "granted_agent_last_monty_execution_milliseconds "
            f"{self._last_monty_execution_ms:.3f}"
        )
        lines.append(
            "granted_agent_server_time_to_first_action_milliseconds "
            f"{self._last_server_ttfa_ms:.3f}"
        )
        lines.append(
            "granted_agent_client_time_to_first_action_milliseconds "
            f"{self._last_client_ttfa_ms:.3f}"
        )
        effective_ttfa = self._last_client_ttfa_ms or self._last_server_ttfa_ms
        lines.append(f"granted_agent_time_to_first_action_milliseconds {effective_ttfa:.3f}")
        lines.append(f"granted_agent_ttfa_slo_milliseconds {self._ttfa_slo_ms:.3f}")
        lines.append(
            "granted_agent_ttfa_slo_met "
            + ("1" if effective_ttfa <= self._ttfa_slo_ms else "0")
        )
        content = "\n".join(lines) + "\n"
        last_error: PermissionError | None = None
        for attempt in range(6):
            temporary = self.metrics_path.with_name(
                f"{self.metrics_path.name}.{uuid.uuid4().hex}.tmp"
            )
            temporary.write_text(content, encoding="utf-8")
            try:
                temporary.replace(self.metrics_path)
                return
            except PermissionError as error:
                last_error = error
                try:
                    temporary.unlink(missing_ok=True)
                except PermissionError:
                    pass
                time.sleep(0.01 * (attempt + 1))
        assert last_error is not None
        raise last_error

    def trajectory(self, request_id: str, payload: dict[str, Any]) -> Path:
        self.trajectory_dir.mkdir(parents=True, exist_ok=True)
        safe_id = "".join(character for character in request_id if character.isalnum() or character in "-_")
        path = self.trajectory_dir / f"{self.now().replace(':', '-')}_{safe_id}.json"
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
        return path
